apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  db-host: bXlwb3N0Z3Jlc3FsLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw=
  db-port: NTQzMg==
  db-user: cG9zdGdyZXM=
  db-password: cGdwYXNz
  db-name: cG9zdGdyZXM=
